spring:
    application:
        name: OneAndMulti
---
bot:
    Name: ${TELEGRAM_BOT_NAME}
    Token: ${TELEGRAM_BOT_TOKEN}
spring:
    application:
        name: botShmel
middleService:
    url: http://localhost:8088
server:
    port: 8080
---
spring:
    application:
        name: middle
server:
    port: 8088
backendService:
    url: http://localhost:8089